name: check-publish
description: check if it should publish the build
runs:
  using: 'composite'
  steps:
    - name: check publish
      id: check-publish
      shell: bash

      run: |
        echo "should publish ..."
        echo version BUILD_VERSION ${{needs.version.outputs.BUILD_VERSION}}
        echo version-test BUILD_VERSION ${{needs.version-test.outputs.BUILD_VERSION}}


  check-publish:
    needs: [version, test]
    name: check publish

    runs-on: ubuntu-latest
    if: >-
      github.actor != 'dependabot[bot]' &&
      github.actor == 'hauner' && contains(needs.version.outputs.BUILD_VERSION, 'SNAPSHOT')

    steps:
      - run: |
          echo "should publish ..."
          echo version BUILD_VERSION ${{needs.version.outputs.BUILD_VERSION}}
          echo version-test BUILD_VERSION ${{needs.version-test.outputs.BUILD_VERSION}}